### ISSUE TITLE
 Recommendation to vendor the C headers and source into the repo

### ISSUE THREAD

**Issue by ethanholz** [tensorush/zig-spin#2]
One big issue I find with packaging project is that the build is also responsible for generating the source and headers from WIT files. However, this is not done by any of the upstream SDKs. For example:
- [spin-dotnet-sdk](https://github.com/fermyon/spin-dotnet-sdk/tree/b438dd5426b947ea7b1141fc5eb8a053479ddf86/src/native)
- [spin-go-sdk](https://github.com/fermyon/spin-go-sdk/tree/48ddef7a261725f771f987323b213b0696c655ef/http)

By vendoring the code, this would not require that end-users to have `wit-bindgen` installed and would be much easier to consume from Zig. Is this something this project would be interested in doing?

I would love to leverage this project in [zig-fermyon-router](https://github.com/ethanholz/zig-fermyon-router) over WAGI, but not having this packaged makes this difficult to do. I am interested in helping to contribute changes to make this happen as well!

**Comment by tensorush** [comment]
I agree. I've committed the WIT C bindings to the repo in `src/include/`. I'll be updating to Zig master next. Nice project, I'll use it to test out whether the packaging of this library works then. Cheers!

**Comment by ethanholz** [comment]
Awesome! Thanks!

**Comment by tensorush** [comment]
Hey, so I got my old simple package test to work for the first time:

https://github.com/tensorush/zig-spin/tree/main/test

It can be run like this:

```sh
cd test/
zig build test -Dup
```

Just thought I'd give you a heads-up on this. I was actually thinking of implementing a basic router as part of the http component like it's been done in the [Go SDK](https://github.com/fermyon/spin-go-sdk/tree/main/examples/http-router).

**Comment by ethanholz** [comment]
Good stuff! This is awesome to see and I am very excited to start porting my router to use this SDK instead.

No worries about implementing a router as an example, I think that the goal of `zig-fermyon-router` is for it to be a bit more "batteries-included". Thank you for the awesome work here!
