### ISSUE TITLE
Full example of standalone build

### ISSUE THREAD

**Issue by itowlson** [tensorush/zig-spin#3]
Kia ora @tensorush, I'm excited to see this and try it out!  Unfortunately I stumbled at a pretty early fence and wondered if you could advise.

I created a `build.zig.zon` as you described, and a `build.zig` although I had to expand it a bit from the README.  I think I followed the repo's `build.zig` but might have got something wrong.  (Details of both below.)  My `src/main.zig` is copied exactly from `examples/http-in` in this repo.  It builds and produces a `.wasm` output, and `spin up` runs, but the Wasm module traps when I curl it.

Is it possible to get a full example of using the Zig Spin SDK from a codebase outside the SDK itself please?  (I'm happy to send a PR once I get something working... I'm just a bit stuck for now.)

### Additional information

Zig version: 0.12.0
Spin version: local build from current source
Host OS: Ubuntu 22.04 (on WSL)
Build command: `zig build`

My `build.zig.zon`:

```
.{
    .name = "example",
    .version = "0.0.1",
    .dependencies = .{
        .spin = .{
            .url = "https://github.com/tensorush/zig-spin/archive/refs/tags/v0.7.0.tar.gz",
            .hash = "12206d63934cce31aa5d8a4d5c7fd52643b537cda89af057bb6ccae232d17cb31ad5",
        },
    },
    .paths = .{
        "src/",
        "build.zig",
        "build.zig.zon",
    },
}
```

My `build.zig` (which is where I'm guessing I went wrong):

```
const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.resolveTargetQuery(.{
        .cpu_arch = .wasm32,
        .os_tag = .wasi,
    });

    const exe = b.addExecutable(.{
        .name = "example",
        .root_source_file = .{ .path = "src/main.zig" },
        .target = target,
    });

    const spin_dep = b.dependency("spin", .{});
    const spin_mod = spin_dep.module("spin");
    exe.root_module.addImport("spin", spin_mod);

    b.installArtifact(exe);
}
```

The trap error that Spin prints:

```
ERROR spin_trigger_http: Error processing request: error while executing at wasm backtrace:
    0: 0x9b57 - <unknown>!spin_http_handle_http_request
    1: 0x2178 - <unknown>!__wasm_export_spin_http_handle_http_request
    2: 0x3fbcb - wit-component:adapter:wasi_snapshot_preview1!fermyon:spin/inbound-http#handle-request
note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information

Caused by:
    wasm trap: uninitialized element
```

(This makes me wonder if `main` has not run and set `spin.http.HANDLER` but I'm not sure if that's right or why it would be.)

Thanks for your help!

**Comment by tensorush** [comment]
Hi! I'm so excited you wanted to give it a try!

In short, you're building the executable in the default `.Debug` optimization mode, instead of `.ReleaseSmall` mode, which is often a crucial detail when building any WASM applications. So you only have to add another field to `addExecutable`'s options like so:

```zig
const exe = b.addExecutable(.{
    .name = "example",
    .root_source_file = .{ .path = "src/main.zig" },
    .target = target,
    .optimize = .ReleaseSmall,
});
```

In fact, this repo already has  a standalone test of this package in `test/` directory with `test/src/main.zig` also being copied exactly from `examples/http-in`. You can run it, meaning both build the WASM executable as well as run `spin up`, with the following single command:

```sh
cd test/
zig build exe -Dup
```

**Comment by itowlson** [comment]
"I'm not concerned about optimising yet," I thought. "I don't need to worry about that field," I thought.

Naturally, it worked like a charm - completely smooth, first time.  Thanks so much!  And thanks for the pointer to the existing standalone sample.

Would you be open to a documentation PR adding these extra details to the README?

**Comment by tensorush** [comment]
Happy to help!

Yes, of course, actually there should be a whole section about important details. I'll add it now, feel free to propose any changes!
